"""
Highly divisible triangular number
   
Problem 12

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

import time
start_time = time.time()

def divisors(x):
    # x = number of divisors
    # return a list with the first triangle number with x divisors
    dl = [1, ]                      # divisors list
    tn = 1                          # triangle number
    s = 1                           # step, to calculate triangle number
    while len(dl) < x:
        for d in range(2, tn // 2 + 1):
            if tn % d == 0:
                dl.append(d)
        dl.append(tn)
        if len(dl) < x:
            dl = [1, ]
            s += 1
            tn += s
        else:
            pass
    return [tn, dl]

print(divisors(500))

print("--- %s seconds ---" % (time.time() - start_time))

    
